###############################################################################
#  Copyright (c) 2019-2026 Joel de Guzman. All rights reserved.
#
#  Distributed under the MIT License (https://opensource.org/licenses/MIT)
###############################################################################
add_subdirectory(gain)
add_subdirectory(delay)
add_subdirectory(va_synth_1)
add_subdirectory(va_synth_2)
add_subdirectory(va_synth_3)
add_subdirectory(va_synth_4)
