= Pulse Wave Synthesizer

include::../../common.adoc[]

== Overview

The pulse wave synthesizer programmatically generates a pulse waveform with specified pulse width. The `basic_pulse_synth` is not bandwidth limited, while `pulse_synth` is, using a technique called "PolyBLEP" to reduce aliasing artifacts that can occur when generating the waveform with a sharp discontinuity as the signal transitions from -1.0 to 1.0.

PolyBLEP works by precalculating a correction function that subtracts the waveform's high-frequency components at discontinuities. This correction function is then applied to the generated waveform, effectively removing frequencies above the waveform's Nyquist frequency to avoid aliasing artifacts.

== Include

```c++
#include <q/synth/pulse_synth.hpp>
```

== Declaration

```c++
struct basic_pulse_synth
{
   constexpr         basic_pulse_synth(float width = 0.5);

   constexpr void    width(float width);
   constexpr float   operator()(phase p);
   constexpr float   operator()(phase_iterator i);
};

struct pulse_synth : basic_pulse_synth
{
   constexpr         pulse_synth(float width = 0.5);

   constexpr float   operator()(phase p, phase dt) const;
   constexpr float   operator()(phase_iterator i) const;
};
```

== Expressions

`basic_pulse_synth` is a model of `{basic_synth}` and implements all valid expressions of `{basic_synth}`. `pulse_synth` is a model of `{bandlimited_synth}` and implements all valid expressions of `{bandlimited_synth}`.

In addition to valid expressions for {basic_synth} and `{bandlimited_synth}`, `basic_pulse_synth` and `pulse_synth` allow these expressions.

=== Notation

`w`   :: A scalar value from 0.0 to 1.0 representing pulse width.
`ps`  :: Object of type `basic_pulse_synth` or `pulse_synth`

=== Constructor

[cols="1,1"]
|===
| Expression               | Semantics

| `basic_pulse_synth(w)`   | Construct a `basic_pulse_synth` given a pulse width, `w`
| `pulse_synth(w)`         | Construct a `pulse_synth` given a pulse width, `w`
|===

NOTE: C++ brace initialization may also be used.

=== Mutators

[cols="1,1"]
|===
| Expression      | Semantics

| `ps.width(w)`   | Set the `basic_pulse_synth` or `pulse_synth` pulse width to `w`.
|===

