= Saw-Tooth Wave Synthesizer

include::../../common.adoc[]

== Overview

The saw-tooth wave synthesizer programmatically generates the waveform. The result is basically just the phase, centered around zero, producing an amplitude of ±1.0. The `basic_saw_synth` is not bandwidth limited, while `saw_synth` is, using a technique called "PolyBLEP" to reduce aliasing artifacts that can occur when generating the waveform with a sharp discontinuity as the signal transitions from -1.0 to 1.0.

PolyBLEP works by precalculating a correction function that subtracts the waveform's high-frequency components at discontinuities. This correction function is then applied to the generated waveform, effectively removing frequencies above the waveform's Nyquist frequency to avoid aliasing artifacts.

== Include

```c++
#include <q/synth/saw_synth.hpp>
```

== Declaration

```c++
struct basic_saw_synth
{
    constexpr float operator()(phase p) const;
    constexpr float operator()(phase_iterator i) const;
};

constexpr auto basic_saw = basic_saw_synth{};

struct saw_synth
{
    constexpr float operator()(phase p, phase dt) const;
    constexpr float operator()(phase_iterator i) const;
};

constexpr auto saw = saw_synth{};
```

== Expressions

`basic_saw_synth` is a model of `{basic_synth}` and implements all valid expressions of `{basic_synth}`. `saw_synth` is a model of `{bandlimited_synth}` and implements all valid expressions of `{bandlimited_synth}`.

`basic_saw_synth` and  `saw_synth` are stateless. The global instances `basic_saw` and `saw` can be used anywhere without needing to be placed in a class or struct. They are semantically equivalent to global functions.


