= lowshelf

include::../../common.adoc[]

Low shelf second-order IIR (Infinite Impulse Response) filter. All frequencies below the shelving frequency are either boosted or attenuated by the specified gain in decibels.

== Include

```c++
#include <q/fx/biquad.hpp>
```

== Declaration

```c++
struct lowshelf : biquad
{
         lowshelf(double db_gain, frequency f, float sps, double q = 0.707);
   void  config(double db_gain, frequency f, float sps, double q = 0.707);
};
```

:biquad: xref:reference/biquad.adoc[biquad]

== Expressions

In addition to valid expressions for {biquad}, `lowshelf` allows these expressions.

=== Notation

`ls`     :: Instance of `bandpass_csg`.
`f`      :: Instance of `frequency`.
`sps`    :: Samples per second.
`q`      :: Q or quality factor.
`g`      :: gain (in decibels).

=== Construction

[cols="1,1"]
|===
| Expression               | Semantics

| `lowshelf(g, f, sps)`    |  Construct a `lowshelf` from `g`, `f`, `sps`. `q` defaults to `0.707`
| `lowshelf(g, f, sps, q)` |  Construct a `lowshelf` from `g`, `f`, `sps` and `q`.
|===

NOTE: C++ brace initialization may also be used.

=== Configuration

[cols="1,1"]
|===
| Expression               | Semantics

| `ls.config(g, f, sps)`   |  Configure a `lowshelf` from `g`, `f`, `sps`. `q` defaults to `0.707`
| `ls.config(g, f, sps, q)`|  Configure a `lowshelf` from `g`, `f`, `sps` and `q`.
|===
