= Low Shelf Filter

include::../../common.adoc[]

== Overview

Low shelf second-order IIR (Infinite Impulse Response) filter. All frequencies below the shelving frequency are either boosted or attenuated by the specified gain in decibels. This filter is embodied by the `lowshelf` class.

== Include

```c++
#include <q/fx/biquad.hpp>
```

== Declaration

```c++
struct lowshelf : biquad
{
         lowshelf(double db_gain, frequency f, float sps, double q = 0.707);
   void  config(double db_gain, frequency f, float sps, double q = 0.707);
};
```

:biquad: xref:reference/biquad.adoc[biquad]

== Expressions

In addition to valid expressions for {biquad}, `lowshelf` allows these expressions.

=== Notation

`ls`              :: Object of type `lowshelf`.
`f`               :: Object of type `frequency`.
`sps`             :: Floating point value representing samples per second.
`q`               :: Q or quality factor.
`g`               :: gain (in decibels).
`a [, b, c, d]`   :: Required `a`, optional `b, c, d`.

=== Constructor

[cols="1,1"]
|===
| Expression                     | Semantics

| `lowshelf(g, f, sps [, q])`    |  Construct a `lowshelf` from `g`, `f`, `sps` and optional `q` (defaults to `0.707`).
|===

NOTE: C++ brace initialization may also be used.

=== Mutators

[cols="1,1"]
|===
| Expression                     | Semantics

| `ls.config(g, f, sps [, q])`   |  Configure a `lowshelf` from `g`, `f`, `sps` and optional `q` (defaults to `0.707`).
|===
