= Q Audio DSP Library

== Introduction

Q is a cross-platform C++ library for Audio Digital Signal Processing. Aptly named after the "Q factor", a dimensionless parameter that describes the quality of a resonant circuit, the Q DSP Library is designed to be simple and elegant, as the simplicity of its name suggests, and efficient enough to run
on small microcontrollers.

Q leverages the power of modern C++ and efficient use of functional
programming techniques, especially function composition using fine-grained and reusable function objects (both stateless and stateful), to simplify complex DSP programming tasks without sacrificing readability.

Q is the host of some experimental Music related DSP facilities <<_the_author>> has accumulated over the years as part of research and development, and will continue to evolve to accommodate more facilities necessary for the fulfillment of various Music related projects.

The library is Open Source and released under the very liberal
http://tinyurl.com/p6pekvo[MIT license].

== Documentation

. https://cycfi.github.io/q/design[Design and Architecture]
. https://cycfi.github.io/q/setup[Setup and Installation]
. https://cycfi.github.io/q/hello_world[Hello, World]
. https://cycfi.github.io/q/hello_universe[Hello, Universe]
. https://cycfi.github.io/q/fundamentals[Fundamentals]

== The Author

Joel got into electronics and programming in the 80s because almost
everything in music, his first love, is becoming electronic and digital. Since then, he builds his own guitars, effect boxes and synths. He enjoys playing distortion-laden rock guitar, composes and produces his own music in his home studio.

Joel de Guzman is the principal architect and engineer at https://www.cycfi.com/[Cycfi Research] and a consultant at https://ciere.com/[Ciere Consulting]. He is a software engineer specializing in advanced C++ and an advocate of Open Source. He has authored a number of highly successful Open Source projects such as http://tinyurl.com/ydhotlaf[Boost.Spirit], http://tinyurl.com/y6vkeo5t[Boost.Phoenix] and http://tinyurl.com/ybn5oq9v[Boost.Fusion].
These libraries are all part of the http://tinyurl.com/jubgged[Boost Libraries], a well respected, peer-reviewed, Open Source, collaborative development effort.

'''

_Copyright (c) 2014-2023 Joel de Guzman. All rights reserved._
_Distributed under the https://opensource.org/licenses/MIT[MIT License]_
