= period

include::../../common.adoc[]

Type safe representation of period: the reciprocal of frequency, or the time it takes for a periodic event to complete one full cycle or oscillation.

== Include

```c++
#include <q/support/period.hpp>
```

== Declaration

`period` is a subclass of xref:reference/units/duration.adoc#value[`duration`].

```c++
struct period : duration
{
   using duration::duration;

   constexpr   period(duration d);
   constexpr   period(frequency f);
};
```

:Value:  xref:reference/units.adoc#value[Value]

== Expressions

In addition to valid expressions for {Value}, `period` allows these expressions.

=== Notation

`d`   :: Object of type `duration`
`f`   :: Object of type `frequency`
`p`   :: Object of type `period`

=== Constructor

[cols="1,1"]
|===
| Expression   | Semantics

| `phase(d)`   | Construct a `period` given a duration, `d`
| `phase(f)`   | Construct a `period` given a frequency, `f`
|===

NOTE: C++ brace initialization may also be used.

=== Conversions

[cols="1,1,1"]
|===
| Expression      | Semantics                         | Return Type

| `as_float(f)`   | Convert frequency to a scalar.    | `float`
| `as_double(f)`  | Convert frequency to a scalar.    | `double`
|===
