= pitch

:keys: image:keys.svg[alt="440Hz Phase Increments", width=125, role=right]

{keys} `pitch` is determined by its position on the chromatic scale, which is a system of 12 notes that repeat in octaves. The distance between each pitch on the chromatic scale is a semitone, and each pitch represents a specific frequency measured in hertz (Hz).

The `pitch` struct includes construction from `frequency` as well as scalars representing the absolute position in the chromatic scale from the base frequency of `8.1757989156437` Hz, which is an octave below F#0. The constructors support both fixed (integer) positions (e.g. 48 semitones) above the base frequency, and fractional positions (e.g. 120.6 semitones) above the base frequency.

Take note that `pitch` works in a logarithmic scale that is base 2. The frequency range is divided into octaves —logarithmic frequency intervals where each octave doubles in frequency. The `pitch` struct includes conversions to and from `frequency`. Q provides fast log2 and pow2 computations using fast math functions.

== Include

```c++
#include <q/support/pitch.hpp>
```

== Declaration

```c++
struct pitch
{
   constexpr static auto base_frequency = frequency{8.1757989156437};

   constexpr            pitch();
   explicit             pitch(frequency f);
   constexpr            pitch(int val);
   constexpr            pitch(float val);
   constexpr            pitch(double val);

   constexpr explicit   operator bool() const;
   constexpr bool       valid() const;

                        template <typename T>
   constexpr pitch&     operator+=(basic_interval<T> b);

                        template <typename T>
   constexpr pitch&     operator-=(basic_interval<T> b);

   double rep = 0.0f;
};

// Free functions
frequency            as_frequency(pitch n);
float                as_float(pitch n);
double               as_double(pitch n);

template <typename T>
constexpr pitch      operator-(pitch a, basic_interval<T> b);

template <typename T>
constexpr pitch      operator+(basic_interval<T> a, pitch b);

template <typename T>
constexpr pitch      operator+(pitch a, basic_interval<T> b);

constexpr bool       operator==(pitch a, pitch b);
constexpr bool       operator!=(pitch a, pitch b);
constexpr bool       operator<(pitch a, pitch b);
constexpr bool       operator<=(pitch a, pitch b);
constexpr bool       operator>(pitch a, pitch b);
constexpr bool       operator>=(pitch a, pitch b);

constexpr pitch      round(pitch n);
constexpr pitch      ceil(pitch n);
constexpr pitch      floor(pitch n);
```

:NonLinearValue:  xref:reference/units.adoc#nonlinearvalue[NonLinearValue]
:Intervals:       xref:reference/units/intervals.adoc[Intervals]

=== Expressions

In addition to valid expressions for `NonLinearValue`, `pitch` allows these expressions.

==== Notation

`p`   :: Instance of `pitch`
`i`   :: Instance of `basic_interval<T>`.

==== Arithmetic

`pitch` extends `NonLinearValue` and allows a very restricted set of arithmetic operations with `pitch` and `basic_interval<T>` operands (see {Intervals}).

[cols="1,1,1"]
|===
| Expression   | Semantics                                     | Return Type

| `p += i`     | Add assign.                                   | `pitch&`
| `p -= i`     | Subtract assign.                              | `pitch&`
| `i + p`      | Addition.                                     | `pitch`
| `p + i`      | Addition.                                     | `pitch`
| `p - i`      | Subtraction.                                  | `pitch`

|===

==== Conversions

[cols="1,1,1"]
|===
| Expression         | Semantics                               | Return Type

| `as_float(p)`      | Convert `pitch` to a scalar.            | `float`
| `as_double(p)`     | Convert `pitch` to a scalar.            | `double`
| `as_frequency(p)`  | Convert `pitch` to a `frequency`.       | `frequency`

|===

==== Functions

[cols="1,1,1"]
|===
| Expression         | Semantics                               | Return Type

| `round(p)`         | Rounds a `pitch` to the nearest
                       non-fractional `pitch`.                 | `pitch`
| `ceil(p)`          | Returns the smallest non-fractional
                       `pitch` that is greater than or equal
                       to a given `pitch`                      | `pitch`
| `floor(p)`         | Returns the largest non-fractional
                       `pitch` that is less than or equal
                       to a given `pitch`                      | `pitch`

|===