= pitch

include::../../common.adoc[]

:keys: image:keys.svg[alt="440Hz Phase Increments", width=125, role=right]

{keys} Pitch is determined by its position on the chromatic scale, which is a system of 12 notes that repeat in octaves. The distance between each pitch on the chromatic scale is a semitone, and each pitch represents a specific frequency measured in hertz (Hz) using 12-tone equal temperament (12-TET).

Pitch is represented as an `interval` with an implied base frequency of `8.1757989156437` Hz that corresponds to MIDI note 0 (which is an octave below F#0), and is therefore represented by the MIDI value. Only positive values are valid.

12-TET conversion functions to and from `interval` and `frequency` are provided. `pitch(f)` is a function that constructs an `interval` from `frequency`. `as_frequency(i)` converts a `basic_interval<T>` to `frequency`. These functions utilize fast log2 and pow2 computations using fast math functions.

== Include

```c++
#include <q/support/pitch.hpp>
```

== Declaration

```c++
constexpr auto base_pitch_frequency = frequency{8.1757989156437};

constexpr interval   invalid_pitch();
interval             pitch(frequency f);

                     template <typename T>
constexpr bool       is_valid_pitch(basic_interval<T> i);

                     template <typename T>
frequency            as_frequency(basic_interval<T> i);
```

=== Expressions

In addition to valid expressions for `interval`, `pitch` allows these expressions.

==== Notation

`i`      :: Object of type `basic_interval<T>`.
`f`      :: Object of type `frequency`.

==== Conversions

[cols="1,1,1"]
|===
| Expression         | Semantics                         | Return Type

| `pitch(f)`         | Convert `f` to an interval.       | `basic_interval<T>`
| `invalid_pitch()`  | Make an invalid interval. This
                       can be used to indicate an
                       invalid state chacked using
                       `is_valid_pitch` (for e.g.
                       pitch-detection).                 | `basic_interval<T>`
| `as_frequency(i)`  | Convert `i` to a `frequency`.     | `frequency`
|===

==== Functions

[cols="1,1,1"]
|===
| Expression            | Semantics                               | Return Type

| `is_valid_pitch(i)`   | Return `true` is `i` is a valid pitch   | `bool`


|===

